apiVersion: batch/v1

kind: CronJob

metadata:

  name: {{ include "owasp1.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "owasp1.name" . }}
    helm.sh/chart: {{ include "owasp1.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

spec:

  schedule: {{ .Values.cronjob.schedule | quote }}

  jobTemplate:

    spec:

      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ include "owasp1.name" . }}
            app.kubernetes.io/instance: {{ .Release.Name }}

        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 8 }}
          {{- end }}

          volumes:
            - name: task-pv-storage3
              persistentVolumeClaim:
                claimName: {{ .Values.pvc.name }}


          containers:

          - name: {{ .Chart.Name }}
            image: "{{ .Values.zapcli.image.repository }}:{{ .Values.zapcli.image.tag }}"
            env:
              - name: auth_username
                valueFrom:
                  secretKeyRef:
                    name: mysecret
                    key: auth_username
                    optional: false
              - name: auth_password
                valueFrom:
                  secretKeyRef:
                    name: mysecret
                    key: auth_password
                    optional: false
              - name: target
                valueFrom:
                  secretKeyRef:
                    name: mysecret
                    key: target
                    optional: false
              - name: reportx
                valueFrom:
                  secretKeyRef:
                    name: mysecret
                    key: reportx
                    optional: false
              - name: configfile
                valueFrom:
                  secretKeyRef:
                    name: mysecret
                    key: configfile
                    optional: false
              - name: duree
                valueFrom:
                  secretKeyRef:
                    name: mysecret
                    key: duree
                    optional: false
              - name: auth_loginurl
                valueFrom:
                  secretKeyRef:
                    name: mysecret
                    key: auth_loginurl
                    optional: false
              - name: key_field_username
                valueFrom:
                  secretKeyRef:
                    name: mysecret
                    key: key_field_username
                    optional: false
              - name: key_field_password
                valueFrom:
                  secretKeyRef:
                    name: mysecret
                    key: key_field_password
                    optional: false
              - name: value_field_username
                valueFrom:
                  secretKeyRef:
                    name: mysecret
                    key: value_field_username
                    optional: false
              - name: value_field_password
                valueFrom:
                  secretKeyRef:
                    name: mysecret
                    key: value_field_password
                    optional: false
              - name: submit_button_input
                valueFrom:
                  secretKeyRef:
                    name: mysecret
                    key: submit_button_input
                    optional: false
              - name: key_field_submit
                valueFrom:
                  secretKeyRef:
                    name: mysecret
                    key: key_field_submit
                    optional: false
              - name: value_field_submit
                valueFrom:
                  secretKeyRef:
                    name: mysecret
                    key: value_field_submit
                    optional: false
              - name: sender_email
                valueFrom:
                  secretKeyRef:
                    name: mysecret
                    key: sender_email
                    optional: false
              - name: receiver_email
                valueFrom:
                  secretKeyRef:
                    name: mysecret
                    key: receiver_email
                    optional: false
              - name: password_email
                valueFrom:
                  secretKeyRef:
                    name: mysecret
                    key: password_email
                    optional: false
                - name: port_email
                valueFrom:
                  secretKeyRef:
                    name: mysecret
                    key: port_email
                    optional: false
              - name: server_email
                valueFrom:
                  secretKeyRef:
                    name: mysecret
                    key: server_email
                    optional: false
              - name: key_field_first_submit
                valueFrom:
                  secretKeyRef:
                    name: mysecret
                    key: key_field_first_submit
                    optional: yes
              - name: value_field_first_submit
                valueFrom:
                  secretKeyRef:
                    name: mysecret
                    key: value_field_first_submit
                    optional: yes
              - name: cookies_button_input
                valueFrom:
                  secretKeyRef:
                    name: mysecret
                    key: cookies_button_input
                    optional: yes
              - name: value_field_poopup
                valueFrom:
                  secretKeyRef:
                    name: mysecret
                    key: value_field_poopup
                    optional: yes
              - name: key_field_poopup
                valueFrom:
                  secretKeyRef:
                    name: mysecret
                    key: key_field_poopup
                    optional: yes

            imagePullPolicy: {{ .Values.zapcli.image.pullPolicy }}
            command: ["run1.sh"]

            volumeMounts:
                - mountPath: "/zap/wrk"
                  name: task-pv-storage3

            
            

          restartPolicy: Never
