apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.name | quote }}
  labels:
    type: local
spec:
  storageClassName: {{ .Values.pv.storageClassName | quote }}
  capacity:
    storage: {{ .Values.pv.storage | quote }}
  accessModes:
    - {{ .Values.pv.accessmode | quote }}
  hostPath:
    path: {{ .Values.pv.path | quote }}
