apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name | quote }}
spec:
  storageClassName: {{ .Values.pvc.storageClassName | quote }}
  accessModes:
    - {{ .Values.pvc.accessmode | quote }}
  resources:
    requests:
      storage: {{ .Values.pvc.capacity | quote }}
