apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  labels:
    app: {{ include "owasp1.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  auth_password: {{ quote .Values.zapcli.cred.password | b64enc }}
  auth_username: {{ quote .Values.zapcli.cred.username | b64enc }}
  target: {{ quote .Values.zapcli.target.home | b64enc }}
  reportx: {{ quote .Values.zapcli.report.name | b64enc }}
  configfile: {{ quote .Values.zapcli.configfile.name | b64enc }}
  duree: {{ quote .Values.zapcli.duree.value | b64enc }}
  auth_loginurl: {{ quote .Values.zapcli.target.loginpage | b64enc }}
  key_field_username: {{ quote .Values.zapcli.fields.key_field_username | b64enc }}
  key_field_password: {{ quote .Values.zapcli.fields.key_field_password | b64enc }}
  value_field_username: {{ quote .Values.zapcli.fields.value_field_username | b64enc }}
  value_field_password: {{ quote .Values.zapcli.fields.value_field_password | b64enc }}
  submit_button_input: {{ quote .Values.zapcli.submit.submit_button_input | b64enc }}
  key_field_submit: {{ quote .Values.zapcli.submit.key_field_submit | b64enc }}
  value_field_submit: {{ quote .Values.zapcli.submit.value_field_submit | b64enc }}
  sender_email: {{ quote .Values.zapcli.email.sender | b64enc }}
  receiver_email: {{ quote .Values.zapcli.email.receiver | b64enc }}
  password_email: {{ quote .Values.zapcli.email.password | b64enc }}
  key_field_first_submit: {{ default "" quote .Values.zapcli.steps.key | b64enc }}
  value_field_first_submit: {{ default "" quote .Values.zapcli.steps.value | b64enc }}
  cookies_button_input: {{ default "" quote .Values.zapcli.cookies.type | b64enc }}
  value_field_poopup: {{ default "" quote .Values.zapcli.cookies.value | b64enc }}
  key_field_poopup: {{default "" quote .Values.zapcli.cookies.key | b64enc }}

